name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt install crossbuild-essential-riscv64
      - name: Build kernel
        run: |
          . scripts/debug
          make
